modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "Extra Mod Integrations"
authors = "Kneelawk, abbie, KirboEatsFood"
description = "EMI addon adding support for as many mods as possible"
logoFile = "assets/${mod_id}/icon.png"

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "REQUIRED"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "emi"
type = "REQUIRED"
versionRange = "[1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "extra_mod_integrations_core"
type = "REQUIRED"
versionRange = "[0,)"
ordering = "NONE"
side = "BOTH"
